package com.alfa.news.common;

import com.alfa.news.R;

import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

public interface Constants {

    String FIRST_RUN = "FIRST_RUN";
    String RSS_LINK = "https://alfabank.ru/_/rss/_rss.html?subtype=1&category=2&city=21";
    String UPDATE_VERSION = "UPDATE_VERSION";
    String CURRENT_ITEM = "CURRENT_ITEM";
    String UPDATE_RSS = "UPDATE_RSS";
    String ALL_ITEMS = "ALL_ITEMS";
    Long MAX_INTERVAL = 5L;

    String DEFAULT_COUNTRY = Locale.getDefault().getCountry();

    Map<String, Integer> COUNTRY_2_PHONE = new HashMap<String, Integer>() {{
        put("", R.drawable._unknown);
        put("AN", R.drawable.an);
        put("AL", R.drawable.al);
        put("AF", R.drawable.af);
        put("DZ", R.drawable.dz);
        put("AD", R.drawable.ad);
        put("AO", R.drawable.ao);
        put("AG", R.drawable.ag);
        put("AR", R.drawable.ar);
        put("AM", R.drawable.am);
        put("AU", R.drawable.au);
        put("AT", R.drawable.at);
        put("AZ", R.drawable.az);
        put("BS", R.drawable.bs);
        put("BH", R.drawable.bh);
        put("BD", R.drawable.bd);
        put("BB", R.drawable.bb);
        put("BY", R.drawable.by);
        put("BE", R.drawable.be);
        put("BZ", R.drawable.bz);
        put("BJ", R.drawable.bj);
        put("BT", R.drawable.bt);
        put("BO", R.drawable.bo);
        put("BA", R.drawable.ba);
        put("BW", R.drawable.bw);
        put("BR", R.drawable.br);
        put("BN", R.drawable.bn);
        put("BG", R.drawable.bg);
        put("BF", R.drawable.bf);
        put("BI", R.drawable.bi);
        put("KH", R.drawable.kh);
        put("CM", R.drawable.cm);
        put("CA", R.drawable.ca);
        put("CV", R.drawable.cv);
        put("CF", R.drawable.cf);
        put("TD", R.drawable.td);
        put("CL", R.drawable.cl);
        put("CN", R.drawable.cn);
        put("CO", R.drawable.co);
        put("KM", R.drawable.km);
        put("CD", R.drawable.cd);
        put("CG", R.drawable.cg);
        put("CR", R.drawable.cr);
        put("CI", R.drawable.ci);
        put("HR", R.drawable.hr);
        put("CU", R.drawable.cu);
        put("CY", R.drawable.cy);
        put("CZ", R.drawable.cz);
        put("DK", R.drawable.dk);
        put("DJ", R.drawable.dj);
        put("DM", R.drawable.dm);
        put("DO", R.drawable.do_);
        put("EC", R.drawable.ec);
        put("EG", R.drawable.eg);
        put("SV", R.drawable.sv);
        put("GQ", R.drawable.gq);
        put("ER", R.drawable.er);
        put("EE", R.drawable.ee);
        put("ET", R.drawable.et);
        put("FJ", R.drawable.fj);
        put("FI", R.drawable.fi);
        put("FR", R.drawable.fr);
        put("GA", R.drawable.ga);
        put("GM", R.drawable.gm);
        put("GE", R.drawable.ge);
        put("DE", R.drawable.de);
        put("GH", R.drawable.gh);
        put("GR", R.drawable.gr);
        put("GD", R.drawable.gd);
        put("GT", R.drawable.gt);
        put("GN", R.drawable.gn);
        put("GW", R.drawable.gw);
        put("GY", R.drawable.gy);
        put("HT", R.drawable.ht);
        put("HN", R.drawable.hn);
        put("HU", R.drawable.hu);
        put("IS", R.drawable.is);
        put("IN", R.drawable.in);
        put("ID", R.drawable.id);
        put("IR", R.drawable.ir);
        put("IQ", R.drawable.iq);
        put("IE", R.drawable.ie);
        put("IL", R.drawable.il);
        put("IT", R.drawable.it);
        put("JM", R.drawable.jm);
        put("JP", R.drawable.jp);
        put("JO", R.drawable.jo);
        put("KZ", R.drawable.kz);
        put("KE", R.drawable.ke);
        put("KI", R.drawable.ki);
        put("KP", R.drawable.kp);
        put("KR", R.drawable.kr);
        put("KW", R.drawable.kw);
        put("KG", R.drawable.kg);
        put("LA", R.drawable.la);
        put("LV", R.drawable.lv);
        put("LB", R.drawable.lb);
        put("LS", R.drawable.ls);
        put("LR", R.drawable.lr);
        put("LY", R.drawable.ly);
        put("LI", R.drawable.li);
        put("LT", R.drawable.lt);
        put("LU", R.drawable.lu);
        put("MK", R.drawable.mk);
        put("MG", R.drawable.mg);
        put("MW", R.drawable.mw);
        put("MY", R.drawable.my);
        put("MV", R.drawable.mv);
        put("ML", R.drawable.ml);
        put("MT", R.drawable.mt);
        put("MH", R.drawable.mh);
        put("MR", R.drawable.mr);
        put("MU", R.drawable.mu);
        put("MX", R.drawable.mx);
        put("FM", R.drawable.fm);
        put("MD", R.drawable.md);
        put("MC", R.drawable.mc);
        put("MN", R.drawable.mn);
        put("ME", R.drawable.me);
        put("MA", R.drawable.ma);
        put("MZ", R.drawable.mz);
        put("MM", R.drawable.mm);
        put("NA", R.drawable.na);
        put("NR", R.drawable.nr);
        put("NP", R.drawable.np);
        put("NL", R.drawable.nl);
        put("NZ", R.drawable.nz);
        put("NI", R.drawable.ni);
        put("NE", R.drawable.ne);
        put("NG", R.drawable.ng);
        put("NO", R.drawable.no);
        put("OM", R.drawable.om);
        put("PK", R.drawable.pk);
        put("PW", R.drawable.pw);
        put("PA", R.drawable.pa);
        put("PG", R.drawable.pg);
        put("PY", R.drawable.py);
        put("PE", R.drawable.pe);
        put("PH", R.drawable.ph);
        put("PL", R.drawable.pl);
        put("PT", R.drawable.pt);
        put("QA", R.drawable.qa);
        put("RO", R.drawable.ro);
        put("RU", R.drawable.ru);
        put("RW", R.drawable.rw);
        put("KN", R.drawable.kn);
        put("LC", R.drawable.lc);
        put("VC", R.drawable.vc);
        put("WS", R.drawable.ws);
        put("SM", R.drawable.sm);
        put("ST", R.drawable.st);
        put("SA", R.drawable.sa);
        put("SN", R.drawable.sn);
        put("RS", R.drawable.rs);
        put("SC", R.drawable.sc);
        put("SL", R.drawable.sl);
        put("SG", R.drawable.sg);
        put("SK", R.drawable.sk);
        put("SI", R.drawable.si);
        put("SB", R.drawable.sb);
        put("SO", R.drawable.so);
        put("ZA", R.drawable.za);
        put("ES", R.drawable.es);
        put("LK", R.drawable.lk);
        put("SD", R.drawable.sd);
        put("SR", R.drawable.sr);
        put("SZ", R.drawable.sz);
        put("SE", R.drawable.se);
        put("CH", R.drawable.ch);
        put("SY", R.drawable.sy);
        put("TJ", R.drawable.tj);
        put("TZ", R.drawable.tz);
        put("TH", R.drawable.th);
        put("TL", R.drawable.tl);
        put("TG", R.drawable.tg);
        put("TO", R.drawable.to);
        put("TT", R.drawable.tt);
        put("TN", R.drawable.tn);
        put("TR", R.drawable.tr);
        put("TM", R.drawable.tm);
        put("TV", R.drawable.tv);
        put("UG", R.drawable.ug);
        put("UA", R.drawable.ua);
        put("AE", R.drawable.ae);
        put("GB", R.drawable.gb);
        put("US", R.drawable.us);
        put("UY", R.drawable.uy);
        put("UZ", R.drawable.uz);
        put("VU", R.drawable.vu);
        put("VA", R.drawable.va);
        put("VE", R.drawable.ve);
        put("VN", R.drawable.vn);
        put("YE", R.drawable.ye);
        put("ZM", R.drawable.zm);
        put("ZW", R.drawable.zw);
        put("GE", R.drawable.ge);
        put("TW", R.drawable.tw);
        put("AZ", R.drawable.az);
        put("CY", R.drawable.cy);
        put("MD", R.drawable.md);
        put("SO", R.drawable.so);
        put("GE", R.drawable.ge);
        put("CX", R.drawable.cx);
        put("CC", R.drawable.cc);
        put("NF", R.drawable.nf);
        put("NC", R.drawable.nc);
        put("PF", R.drawable.pf);
        put("YT", R.drawable.yt);
        put("WF", R.drawable.wf);
        put("CK", R.drawable.ck);
        put("NU", R.drawable.nu);
        put("TK", R.drawable.tk);
        put("GG", R.drawable.gg);
        put("IM", R.drawable.im);
        put("JE", R.drawable.je);
        put("AI", R.drawable.ai);
        put("BM", R.drawable.bm);
        put("VG", R.drawable.vg);
        put("KY", R.drawable.ky);
        put("FK", R.drawable.fk);
        put("GI", R.drawable.gi);
        put("MS", R.drawable.ms);
        put("SH", R.drawable.sh);
        put("TC", R.drawable.tc);
        put("MP", R.drawable.mp);
        put("PR", R.drawable.pr);
        put("AS", R.drawable.as);
        put("GU", R.drawable.gu);
        put("VI", R.drawable.vi);
        put("HK", R.drawable.hk);
        put("MO", R.drawable.mo);
        put("FO", R.drawable.fo);
        put("GL", R.drawable.gl);
        put("MQ", R.drawable.mq);
        put("AX", R.drawable.ax);
        put("AW", R.drawable.aw);
        put("PS", R.drawable.ps);
        put("EH", R.drawable.eh);
//        put("IO", R.drawable.io);
//        put("GP", R.drawable.gp);
//        put("GF", R.drawable.gf);
//        put("RE", R.drawable.re);
//        put("SJ", R.drawable.sj);
//        put("AC", R.drawable.ac);
//        put("TA", R.drawable.ta);
//        put("CS", R.drawable.cs);
//        put("GP", R.drawable.gp);
//        put("GP", R.drawable.gp);
//        put("PM", R.drawable.pm);
    }};
}
